language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codacy-coverage
script:
  - |
     coverage run --source=app -m pytest app/tests.py -v && \
     coverage report && \
     coverage xml && \
     python-codacy-coverage -r coverage.xml
after_success:
  - coveralls
