language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=app -m pytest app/tests.py -v && coverage report
after_success:
  - coveralls
